image: marcelhuberfoo/cabal-build


stages:
    - build


compile:
    stage: build
    script:
      - pacman -Sy ghc-static
      - cabal update
      - cabal install --only-dependencies
      - cabal build
  
